spring.application.name=file_server
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
fileserver.root-dir=/tmp/server-files

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fileServer_db
spring.datasource.username=admin
spring.datasource.password=server_admin

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.active=local